version: '3.1'

services:
  flask-foundation:
    image: flask-foundation
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    links:
      - database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password