version: '3.1'

services:
  flask-foundation:
    image: flask-foundation
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app/
    links:
      - database
    depends_on:
      - database
    restart: always
  # db:
  #   image: mysql:5.7
  #   ports:
  #     - "32000:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: insta_admin
  #     MYSQL_PASSWORD: insta2018
  #     MYSQL_DATABASE: insta_db


  database:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    command: --disable-partition-engine-check --max_allowed_packet=32505856
    restart: always
    ports:
      - "32000:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ipdb
      MYSQL_PASSWORD: ipdb
      MYSQL_DATABASE: ipdb